basePath: /
host: ws-yoginara-2024-479b633e2c8b.herokuapp.com
info:
  contact:
    email: indra@ulbi.ac.id
    name: API Support
    url: https://github.com/Yoginara
  description: This is a sample swagger for Fiber
  title: TES SWAGGER ULBI
  version: "1.0"
paths: {}
schemes:
- https
- http
swagger: "2.0"
